version: '3.7'
services:
    microservice-db:
        build: 
          context: .
          labels:
            com.mssql.environment: "dev"
          dockerfile: dockerfile
        hostname: microservice-db
        container_name: mssql
        ports:  
          - "15789:1433"
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: